"""add model message

Revision ID: 11f599a7a6ce
Revises: b7f0f816ab58
Create Date: 2023-10-20 09:35:22.390730

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '11f599a7a6ce'
down_revision = 'b7f0f816ab58'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('messages',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('sender', sa.BigInteger(), nullable=True),
    sa.Column('receiver', sa.BigInteger(), nullable=True),
    sa.Column('text', sa.String(length=2048), nullable=False),
    sa.Column('date', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['receiver'], ['users.id'], name='fk_messages_users_id_receiver'),
    sa.ForeignKeyConstraint(['sender'], ['users.id'], name='fk_messages_users_id_sender'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('messages')
    # ### end Alembic commands ###
