"""alter field username on worker

Revision ID: 175d3091e822
Revises: 7968acdbc509
Create Date: 2023-10-14 18:37:18.192142

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '175d3091e822'
down_revision = '7968acdbc509'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('workers', sa.Column('username', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('workers', 'username')
    # ### end Alembic commands ###
