"""add model worker_requests

Revision ID: 221ab48c306a
Revises: 6bebb190a947
Create Date: 2023-10-21 09:55:41.067993

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '221ab48c306a'
down_revision = '6bebb190a947'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('transactions')
    op.add_column('worker_requests', sa.Column('receipt', sa.String(length=1024), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('worker_requests', 'receipt')
    op.create_table('transactions',
    sa.Column('id', sa.BIGINT(), autoincrement=True, nullable=False),
    sa.Column('worker', sa.BIGINT(), autoincrement=False, nullable=True),
    sa.Column('amount', sa.NUMERIC(precision=12, scale=2), autoincrement=False, nullable=True),
    sa.Column('date', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('receipt', sa.VARCHAR(length=1024), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['worker'], ['workers.id'], name='fk_transactions_workers_id_worker'),
    sa.PrimaryKeyConstraint('id', name='transactions_pkey')
    )
    # ### end Alembic commands ###
