"""add model admin_payment_details

Revision ID: 448747c39e4d
Revises: 9a9f9efd72b3
Create Date: 2023-10-23 06:59:23.629788

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '448747c39e4d'
down_revision = '9a9f9efd72b3'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('admin_requests',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('amount', sa.DECIMAL(precision=12, scale=2), nullable=True),
    sa.Column('type', sa.String(length=10), nullable=False),
    sa.Column('date', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('admin_requests')
    # ### end Alembic commands ###
