"""add model worker_requests

Revision ID: 46a84ad115d2
Revises: d6224e58c599
Create Date: 2023-10-21 17:57:41.862127

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '46a84ad115d2'
down_revision = 'd6224e58c599'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('worker_requests', sa.Column('marginal_amount', sa.DECIMAL(precision=12, scale=2), nullable=True))
    op.add_column('worker_requests', sa.Column('worker_amount', sa.DECIMAL(precision=12, scale=2), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('worker_requests', 'worker_amount')
    op.drop_column('worker_requests', 'marginal_amount')
    # ### end Alembic commands ###
