"""add port to worker

Revision ID: 4d282cf06cc8
Revises: 0ed8784facdd
Create Date: 2023-10-12 10:19:47.091771

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4d282cf06cc8'
down_revision = '0ed8784facdd'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('workers', sa.Column('api_port', sa.BigInteger(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('workers', 'api_port')
    # ### end Alembic commands ###
