"""add model worker_requests

Revision ID: 6bebb190a947
Revises: 713051d9e1ef
Create Date: 2023-10-21 09:45:50.665868

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6bebb190a947'
down_revision = '713051d9e1ef'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('worker_requests', sa.Column('is_success', sa.Boolean(), nullable=True))
    op.add_column('worker_requests', sa.Column('comment', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('worker_requests', 'comment')
    op.drop_column('worker_requests', 'is_success')
    # ### end Alembic commands ###
