"""add model worker_requests

Revision ID: 713051d9e1ef
Revises: 71b5bba76570
Create Date: 2023-10-21 09:42:42.619451

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '713051d9e1ef'
down_revision = '71b5bba76570'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('worker_requests',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('worker', sa.BigInteger(), nullable=True),
    sa.Column('amount', sa.DECIMAL(precision=12, scale=2), nullable=True),
    sa.Column('type', sa.String(length=10), nullable=False),
    sa.Column('date', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['worker'], ['workers.id'], name='fk_worker_requests_workers_id_worker'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('worker_requests')
    # ### end Alembic commands ###
