"""add model message

Revision ID: 71b5bba76570
Revises: 11f599a7a6ce
Create Date: 2023-10-20 11:13:24.180093

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '71b5bba76570'
down_revision = '11f599a7a6ce'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
