"""create transitions

Revision ID: 7968acdbc509
Revises: e09fd61665c0
Create Date: 2023-10-14 18:27:13.669273

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7968acdbc509'
down_revision = 'e09fd61665c0'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('transitions',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('worker_name', sa.String(length=255), nullable=False),
    sa.Column('date', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('transitions')
    # ### end Alembic commands ###
