"""add matrix request

Revision ID: a313b4720927
Revises: bb2a975fb461
Create Date: 2023-10-26 13:23:54.540935

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a313b4720927'
down_revision = 'bb2a975fb461'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('matrix_user_requests',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('worker_request', sa.Integer(), nullable=True),
    sa.Column('user', sa.BigInteger(), nullable=True),
    sa.Column('dob', sa.String(length=60), nullable=True),
    sa.Column('image', sa.String(length=2048), nullable=True),
    sa.Column('result', sa.String(length=8096), nullable=True),
    sa.ForeignKeyConstraint(['user'], ['users.id'], name='fk_matrix_user_requests_users_id_user'),
    sa.ForeignKeyConstraint(['worker_request'], ['worker_requests.id'], name='fk_matrix_user_requests_worker_requests_id_worker_request'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('matrix_user_requests')
    # ### end Alembic commands ###
