"""add transactions

Revision ID: b7f0f816ab58
Revises: 4dd8739588cb
Create Date: 2023-10-17 09:26:39.557973

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b7f0f816ab58'
down_revision = '4dd8739588cb'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('transactions', sa.Column('receipt', sa.String(length=1024), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('transactions', 'receipt')
    # ### end Alembic commands ###
