"""remove column comission, has_access ow worker

Revision ID: bb2a975fb461
Revises: e87b3c514dfa
Create Date: 2023-10-24 08:25:37.877631

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bb2a975fb461'
down_revision = 'e87b3c514dfa'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('workers', 'payment_details')
    op.drop_column('workers', 'has_access')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('workers', sa.Column('has_access', sa.VARCHAR(length=1024), autoincrement=False, nullable=True))
    op.add_column('workers', sa.Column('payment_details', sa.VARCHAR(length=1024), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
