"""add model worker_requests

Revision ID: d6224e58c599
Revises: 221ab48c306a
Create Date: 2023-10-21 10:52:19.579605

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd6224e58c599'
down_revision = '221ab48c306a'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('workers', sa.Column('freezed_amount', sa.DECIMAL(precision=12, scale=2), nullable=True))
    op.add_column('workers', sa.Column('payment_details', sa.String(length=1024), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('workers', 'payment_details')
    op.drop_column('workers', 'freezed_amount')
    # ### end Alembic commands ###
