"""add amount to worker and proccing on user

Revision ID: e09fd61665c0
Revises: f42cf88a5523
Create Date: 2023-10-14 18:20:43.095543

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e09fd61665c0'
down_revision = 'f42cf88a5523'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('is_free_consulting', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'is_free_consulting')
    # ### end Alembic commands ###
