"""add column comission, has_access ow worker

Revision ID: e87b3c514dfa
Revises: 448747c39e4d
Create Date: 2023-10-24 07:12:04.673654

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e87b3c514dfa'
down_revision = '448747c39e4d'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('workers', sa.Column('comission', sa.Integer(), nullable=True))
    op.add_column('workers', sa.Column('has_access', sa.String(length=1024), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('workers', 'has_access')
    op.drop_column('workers', 'comission')
    # ### end Alembic commands ###
