"""add amount to worker and proccing on user

Revision ID: f42cf88a5523
Revises: 4d282cf06cc8
Create Date: 2023-10-13 16:53:59.348954

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f42cf88a5523'
down_revision = '4d282cf06cc8'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('is_processing', sa.Boolean(), nullable=True))
    op.add_column('workers', sa.Column('amount', sa.DECIMAL(precision=12, scale=2), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('workers', 'amount')
    op.drop_column('users', 'is_processing')
    # ### end Alembic commands ###
