version: "3"
services:
  tapi:
    build:
      context: './'
      dockerfile: Dockerfile
    container_name: tapi
    depends_on:
      - tdb
    ports:
      - "8000:8000"
    networks:
      - project-network
    entrypoint: /bin/bash -c "sleep 1 && /opt/backend/entrypoint.sh"

  tdb:
    image: postgres:latest
    container_name: tdb
    environment:
      POSTGRES_USER: konstantin
      POSTGRES_PASSWORD: Lp2nZxYOCcPhzrXj
      POSTGRES_DB: tant
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - project-network

networks:
  project-network:

volumes:
  postgres_data:
