"""update service

Revision ID: 8ba7e82f7049
Revises: e67ba7f3f357
Create Date: 2024-03-19 16:35:45.451236

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8ba7e82f7049'
down_revision = 'e67ba7f3f357'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('services_type_fkey', 'services', type_='foreignkey')
    op.create_foreign_key(None, 'services', 'service_types', ['type'], ['idx'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'services', type_='foreignkey')
    op.create_foreign_key('services_type_fkey', 'services', 'service_types', ['type'], ['idx'])
    # ### end Alembic commands ###
