version: "3"
services:
  bot:
    build:
      context: './'
      dockerfile: Dockerfile
    depends_on:
      - db
    ports:
      - "1001:8000"
    networks:
      - project-network
    # entrypoint: /bin/bash -c "sleep 1 && /app/entrypoint.sh"

networks:
  project-network:

volumes:
  postgres_data:
