version: "3"
services:
  bot:
    build:
      context: './'
      dockerfile: Dockerfile
    depends_on:
      - db
    ports:
      - "3490:3490"
    networks:
      - project-network

networks:
  project-network: