"""update botuser

Revision ID: 9ca2fa4822e4
Revises: 8f27fa5c61a0
Create Date: 2024-03-24 13:59:56.711769

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9ca2fa4822e4'
down_revision = '8f27fa5c61a0'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('fk_taro_categories_bots_id_bot', 'taro_categories', type_='foreignkey')
    op.create_foreign_key('fk_taro_categories_bots_id_bot', 'taro_categories', 'bots', ['bot'], ['id'], ondelete='CASCADE')
    op.drop_constraint('fk_taro_services_taro_categories_id_category', 'taro_services', type_='foreignkey')
    op.create_foreign_key('fk_taro_services_taro_categories_id_category', 'taro_services', 'taro_categories', ['category'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('fk_taro_services_taro_categories_id_category', 'taro_services', type_='foreignkey')
    op.create_foreign_key('fk_taro_services_taro_categories_id_category', 'taro_services', 'taro_categories', ['category'], ['id'])
    op.drop_constraint('fk_taro_categories_bots_id_bot', 'taro_categories', type_='foreignkey')
    op.create_foreign_key('fk_taro_categories_bots_id_bot', 'taro_categories', 'bots', ['bot'], ['id'])
    # ### end Alembic commands ###
