"""create models

Revision ID: f606194b6414
Revises: 
Create Date: 2024-04-11 01:24:52.029369

"""
import ormar
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f606194b6414'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('admin_payment_details',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('text', sa.String(length=255), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('admin_requests',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('amount', sa.DECIMAL(precision=12, scale=2), nullable=True),
    sa.Column('type', sa.String(length=10), nullable=False),
    sa.Column('date', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_admin_requests_date'), 'admin_requests', ['date'], unique=False)
    op.create_table('bots',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('uid', ormar.fields.sqlalchemy_uuid.CHAR(32), nullable=True),
    sa.Column('total_users', sa.Integer(), nullable=True),
    sa.Column('amount', sa.DECIMAL(precision=12, scale=2), nullable=True),
    sa.Column('freezed_amount', sa.DECIMAL(precision=12, scale=2), nullable=True),
    sa.Column('comission', sa.Integer(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('uid')
    )
    op.create_table('tgusers',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('username', sa.String(length=255), nullable=True),
    sa.Column('full_name', sa.String(length=255), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('bot_requests',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('bot', sa.BigInteger(), nullable=False),
    sa.Column('amount', sa.DECIMAL(precision=20, scale=2), nullable=True),
    sa.Column('marginal_amount', sa.DECIMAL(precision=20, scale=2), nullable=True),
    sa.Column('worker_amount', sa.DECIMAL(precision=20, scale=2), nullable=True),
    sa.Column('is_success', sa.Boolean(), nullable=True),
    sa.Column('receipt', sa.String(length=1024), nullable=True),
    sa.Column('comment', sa.String(length=255), nullable=True),
    sa.Column('type', sa.String(length=10), nullable=False),
    sa.Column('date', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['bot'], ['bots.id'], name='fk_bot_requests_bots_id_bot'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_bot_requests_date'), 'bot_requests', ['date'], unique=False)
    op.create_table('bot_users',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('bot', sa.BigInteger(), nullable=False),
    sa.Column('tguser', sa.BigInteger(), nullable=False),
    sa.Column('last_activity', sa.DateTime(), nullable=True),
    sa.Column('first_touch', sa.DateTime(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['bot'], ['bots.id'], name='fk_bot_users_bots_id_bot'),
    sa.ForeignKeyConstraint(['tguser'], ['tgusers.id'], name='fk_bot_users_tgusers_id_tguser'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('bot', 'tguser', name='uc_bot_users_bot_tguser')
    )
    op.create_index(op.f('ix_bot_users_first_touch'), 'bot_users', ['first_touch'], unique=False)
    op.create_index(op.f('ix_bot_users_last_activity'), 'bot_users', ['last_activity'], unique=False)
    op.create_table('profiles',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('tguser', sa.BigInteger(), nullable=True),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('password', sa.String(length=255), nullable=True),
    sa.Column('last_activity', sa.DateTime(), nullable=True),
    sa.Column('first_touch', sa.DateTime(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('is_admin', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['tguser'], ['tgusers.id'], name='fk_profiles_tgusers_id_tguser'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_index(op.f('ix_profiles_first_touch'), 'profiles', ['first_touch'], unique=False)
    op.create_index(op.f('ix_profiles_last_activity'), 'profiles', ['last_activity'], unique=False)
    op.create_table('taro_categories',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('bot', sa.BigInteger(), nullable=True),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('photo', sa.String(length=1024), nullable=True),
    sa.Column('parent', sa.BigInteger(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['bot'], ['bots.id'], name='fk_taro_categories_bots_id_bot', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['parent'], ['taro_categories.id'], name='fk_taro_categories_taro_categories_id_parent'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('bots_profiles',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('bot', sa.BigInteger(), nullable=False),
    sa.Column('profile', sa.BigInteger(), nullable=False),
    sa.Column('is_paid', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('next_payment', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['bot'], ['bots.id'], name='fk_bots_profiles_bots_id_bot'),
    sa.ForeignKeyConstraint(['profile'], ['profiles.id'], name='fk_bots_profiles_profiles_id_profile'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('bot', 'profile', name='uc_bots_profiles_bot_profile')
    )
    op.create_index(op.f('ix_bots_profiles_created_at'), 'bots_profiles', ['created_at'], unique=False)
    op.create_index(op.f('ix_bots_profiles_next_payment'), 'bots_profiles', ['next_payment'], unique=False)
    op.create_table('profile_payment_details',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('profile', sa.BigInteger(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('text', sa.String(length=255), nullable=False),
    sa.ForeignKeyConstraint(['profile'], ['profiles.id'], name='fk_profile_payment_details_profiles_id_profile'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('taro_services',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('category', sa.BigInteger(), nullable=True),
    sa.Column('bot', sa.BigInteger(), nullable=True),
    sa.Column('photo', sa.String(length=1024), nullable=True),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.String(length=255), nullable=False),
    sa.ForeignKeyConstraint(['bot'], ['bots.id'], name='fk_taro_services_bots_id_bot'),
    sa.ForeignKeyConstraint(['category'], ['taro_categories.id'], name='fk_taro_services_taro_categories_id_category', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('taro_services')
    op.drop_table('profile_payment_details')
    op.drop_index(op.f('ix_bots_profiles_next_payment'), table_name='bots_profiles')
    op.drop_index(op.f('ix_bots_profiles_created_at'), table_name='bots_profiles')
    op.drop_table('bots_profiles')
    op.drop_table('taro_categories')
    op.drop_index(op.f('ix_profiles_last_activity'), table_name='profiles')
    op.drop_index(op.f('ix_profiles_first_touch'), table_name='profiles')
    op.drop_table('profiles')
    op.drop_index(op.f('ix_bot_users_last_activity'), table_name='bot_users')
    op.drop_index(op.f('ix_bot_users_first_touch'), table_name='bot_users')
    op.drop_table('bot_users')
    op.drop_index(op.f('ix_bot_requests_date'), table_name='bot_requests')
    op.drop_table('bot_requests')
    op.drop_table('tgusers')
    op.drop_table('bots')
    op.drop_index(op.f('ix_admin_requests_date'), table_name='admin_requests')
    op.drop_table('admin_requests')
    op.drop_table('admin_payment_details')
    # ### end Alembic commands ###
