"""update service

Revision ID: 1861b697e4ad
Revises: 8ba7e82f7049
Create Date: 2024-03-19 18:26:13.306564

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1861b697e4ad'
down_revision = '8ba7e82f7049'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
