"""new service logic

Revision ID: 5973287d8e58
Revises: 1861b697e4ad
Create Date: 2024-03-23 11:46:36.105762

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5973287d8e58'
down_revision = '1861b697e4ad'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('service_types', sa.Column('photo', sa.String(length=255), nullable=True))
    op.add_column('services', sa.Column('photo', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('services', 'photo')
    op.drop_column('service_types', 'photo')
    # ### end Alembic commands ###
