"""update user

Revision ID: 60cca9e80313
Revises: 25f53ca1c08d
Create Date: 2024-03-19 14:58:05.933171

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '60cca9e80313'
down_revision = '25f53ca1c08d'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('created_at', sa.DateTime(), nullable=True))
    op.add_column('users', sa.Column('last_active', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'last_active')
    op.drop_column('users', 'created_at')
    # ### end Alembic commands ###
