"""update user

Revision ID: e67ba7f3f357
Revises: 36d42c6dc9e9
Create Date: 2024-03-19 15:37:39.494772

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e67ba7f3f357'
down_revision = '36d42c6dc9e9'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
