"""add taro training

Revision ID: 6bb47ee57fa0
Revises: 05a55473d49b
Create Date: 2023-11-20 12:22:45.999481

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6bb47ee57fa0'
down_revision = '05a55473d49b'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('taro_trainings', sa.Column('is_banned', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('taro_trainings', 'is_banned')
    # ### end Alembic commands ###
