version: "3"
services:
  bot:
    build:
      context: './'
      dockerfile: Dockerfile
    container_name: nallabot
    depends_on:
      - db
    ports:
      - "1002:8000"
    networks:
      - project-network
    # entrypoint: /bin/bash -c "sleep 1 && /app/entrypoint.sh"

  db:
    image: postgres:latest
    container_name: nalladb
    environment:
      POSTGRES_USER: dbuser
      POSTGRES_PASSWORD: dbpassword
      POSTGRES_DB: dbname
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - project-network

networks:
  project-network:

volumes:
  postgres_data:
